title: "Yogesh Sirotia"
email: "ysirotia2@gmail.com"
description: "learning the ways of life through trading. Thoughts and digital products for better living. by yogesh sirotia"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yogeshsirotia.in" # the full URL for your custom domain
theme: minima
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
