title: "yogesh sirotia"
email: "ysirotia2@gmail.com"
description: "Thoughts, work, and digital products by Yogesh Sirotia"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yogeshsirotia.in" # the full URL for your custom domain
theme: minima
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
